/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.IOException;
import java.util.Optional;

public class App {
    public static void main(String[] args) {
        try {
            Quotes quotes = new Quotes("./app/src/main/resources/recentquotes.json");
            Quotes.Quote quote = quotes.getRandomQuote();
            System.out.println("Quote: " + quote.getText());
            System.out.println("Author: " + quote.getAuthor());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

